---
name: lint

on:
  push:
    branches: ["master"]
    paths:
      - '**.py'
  pull_request:
    branches: ["master"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update; sudo apt-get install libkrb5-dev gcc

      - name: Install uv
        uses: astral-sh/setup-uv@v5
        with:
          python-version: "3.13"

      - name: Lint with ruff
        run: uv run ruff check jenkinsapi/ --output-format full
