name: CI_TEST

on:
  push:
    branches: [ "master" ]
    paths:
      - '**.py'
      - '**.yml'
  pull_request:
    branches: [ "master" ]
  workflow_dispatch: # allow manual run

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python
      run: uv python install

    - name: Install dependencies
      run: |
        sudo apt-get update; sudo apt-get install libkrb5-dev gcc

    - name: Lint with ruff
      run: |
        uv run ruff check jenkinsapi/ --output-format full

  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.9", "3.10", "3.11", "3.12", "3.13"]

    steps:
    - name: Harden Runner
      uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
      with:
        egress-policy: audit
        allowed-endpoints: >
          azure.archive.ubuntu.com:80
          esm.ubuntu.com:443
          files.pythonhosted.org:443
          ftp-chi.osuosl.org:443
          ftp-nyc.osuosl.org:443
          get.jenkins.io:443
          github.com:443
          api.github.com:443
          int.api.stepsecurity.io:443
          mirror.xmission.com:443
          motd.ubuntu.com:443
          packages.microsoft.com:443
          ppa.launchpadcontent.net:443
          pypi.org:443
          updates.jenkins-ci.org:80
          updates.jenkins.io:443
          mirrors.updates.jenkins.io:443
          updates.jenkins.io:80

    - name: Checkout
      uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0

    - name: Install uv
      uses: astral-sh/setup-uv@85856786d1ce8acfbcc2f13a5f3fbd6b938f9f41 # v7.1.2
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install python
      run: uv python install

    - name: setup java 21
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5.0.0
      with:
        java-version: '21'
        distribution: 'temurin'

    - name: Install dependencies
      run: |
        sudo apt-get update; sudo apt-get install libkrb5-dev gcc

    - name: Test with pytest
      run: |
        uv run pytest -sv --cov=jenkinsapi --cov-report=term-missing --cov-report=xml jenkinsapi_tests
